name: linting, testing, building
on: 
    push:
      branches: [master]

    pull_requested:
      branches: [master]
        
jobs:
    pipeline:
      runs-on: ubuntu-latest
      strategy:
      matrix:
      node-version: [17.x]


      steps:
      - uses: actions/cheeckout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version:${{ matrix.node-version }}

      - name: install modules 
      run: npm install 
      - name: buildProd
      run: build:prod
      - name: buildDev
      run: build:dev
      - name: lintTypeScript
      run: npm run lint:ts
      - name: lintCSS
      run: npm run lint:scss
      - name: unitTest
      run: npm run test